/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasRouteImport } from './routes/ventas'
import { Route as VacacionesRouteImport } from './routes/vacaciones'
import { Route as LimpiezaRouteImport } from './routes/limpieza'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as EmpleadasRouteImport } from './routes/empleadas'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminVentasRouteImport } from './routes/admin-ventas'
import { Route as AdminVacacionesRouteImport } from './routes/admin-vacaciones'
import { Route as AdminLimpiezaRouteImport } from './routes/admin-limpieza'
import { Route as AdminInsumosRouteImport } from './routes/admin-insumos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VentasRoute = VentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const VacacionesRoute = VacacionesRouteImport.update({
  id: '/vacaciones',
  path: '/vacaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const LimpiezaRoute = LimpiezaRouteImport.update({
  id: '/limpieza',
  path: '/limpieza',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpleadasRoute = EmpleadasRouteImport.update({
  id: '/empleadas',
  path: '/empleadas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVentasRoute = AdminVentasRouteImport.update({
  id: '/admin-ventas',
  path: '/admin-ventas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVacacionesRoute = AdminVacacionesRouteImport.update({
  id: '/admin-vacaciones',
  path: '/admin-vacaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLimpiezaRoute = AdminLimpiezaRouteImport.update({
  id: '/admin-limpieza',
  path: '/admin-limpieza',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsumosRoute = AdminInsumosRouteImport.update({
  id: '/admin-insumos',
  path: '/admin-insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-insumos': typeof AdminInsumosRoute
  '/admin-limpieza': typeof AdminLimpiezaRoute
  '/admin-vacaciones': typeof AdminVacacionesRoute
  '/admin-ventas': typeof AdminVentasRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/empleadas': typeof EmpleadasRoute
  '/insumos': typeof InsumosRoute
  '/limpieza': typeof LimpiezaRoute
  '/vacaciones': typeof VacacionesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-insumos': typeof AdminInsumosRoute
  '/admin-limpieza': typeof AdminLimpiezaRoute
  '/admin-vacaciones': typeof AdminVacacionesRoute
  '/admin-ventas': typeof AdminVentasRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/empleadas': typeof EmpleadasRoute
  '/insumos': typeof InsumosRoute
  '/limpieza': typeof LimpiezaRoute
  '/vacaciones': typeof VacacionesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-insumos': typeof AdminInsumosRoute
  '/admin-limpieza': typeof AdminLimpiezaRoute
  '/admin-vacaciones': typeof AdminVacacionesRoute
  '/admin-ventas': typeof AdminVentasRoute
  '/auth': typeof AuthRoute
  '/clientes': typeof ClientesRoute
  '/empleadas': typeof EmpleadasRoute
  '/insumos': typeof InsumosRoute
  '/limpieza': typeof LimpiezaRoute
  '/vacaciones': typeof VacacionesRoute
  '/ventas': typeof VentasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-insumos'
    | '/admin-limpieza'
    | '/admin-vacaciones'
    | '/admin-ventas'
    | '/auth'
    | '/clientes'
    | '/empleadas'
    | '/insumos'
    | '/limpieza'
    | '/vacaciones'
    | '/ventas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-insumos'
    | '/admin-limpieza'
    | '/admin-vacaciones'
    | '/admin-ventas'
    | '/auth'
    | '/clientes'
    | '/empleadas'
    | '/insumos'
    | '/limpieza'
    | '/vacaciones'
    | '/ventas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-insumos'
    | '/admin-limpieza'
    | '/admin-vacaciones'
    | '/admin-ventas'
    | '/auth'
    | '/clientes'
    | '/empleadas'
    | '/insumos'
    | '/limpieza'
    | '/vacaciones'
    | '/ventas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminInsumosRoute: typeof AdminInsumosRoute
  AdminLimpiezaRoute: typeof AdminLimpiezaRoute
  AdminVacacionesRoute: typeof AdminVacacionesRoute
  AdminVentasRoute: typeof AdminVentasRoute
  AuthRoute: typeof AuthRoute
  ClientesRoute: typeof ClientesRoute
  EmpleadasRoute: typeof EmpleadasRoute
  InsumosRoute: typeof InsumosRoute
  LimpiezaRoute: typeof LimpiezaRoute
  VacacionesRoute: typeof VacacionesRoute
  VentasRoute: typeof VentasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas': {
      id: '/ventas'
      path: '/ventas'
      fullPath: '/ventas'
      preLoaderRoute: typeof VentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacaciones': {
      id: '/vacaciones'
      path: '/vacaciones'
      fullPath: '/vacaciones'
      preLoaderRoute: typeof VacacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limpieza': {
      id: '/limpieza'
      path: '/limpieza'
      fullPath: '/limpieza'
      preLoaderRoute: typeof LimpiezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empleadas': {
      id: '/empleadas'
      path: '/empleadas'
      fullPath: '/empleadas'
      preLoaderRoute: typeof EmpleadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ventas': {
      id: '/admin-ventas'
      path: '/admin-ventas'
      fullPath: '/admin-ventas'
      preLoaderRoute: typeof AdminVentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-vacaciones': {
      id: '/admin-vacaciones'
      path: '/admin-vacaciones'
      fullPath: '/admin-vacaciones'
      preLoaderRoute: typeof AdminVacacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-limpieza': {
      id: '/admin-limpieza'
      path: '/admin-limpieza'
      fullPath: '/admin-limpieza'
      preLoaderRoute: typeof AdminLimpiezaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-insumos': {
      id: '/admin-insumos'
      path: '/admin-insumos'
      fullPath: '/admin-insumos'
      preLoaderRoute: typeof AdminInsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminInsumosRoute: AdminInsumosRoute,
  AdminLimpiezaRoute: AdminLimpiezaRoute,
  AdminVacacionesRoute: AdminVacacionesRoute,
  AdminVentasRoute: AdminVentasRoute,
  AuthRoute: AuthRoute,
  ClientesRoute: ClientesRoute,
  EmpleadasRoute: EmpleadasRoute,
  InsumosRoute: InsumosRoute,
  LimpiezaRoute: LimpiezaRoute,
  VacacionesRoute: VacacionesRoute,
  VentasRoute: VentasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
